# Generated by Django 3.0.6 on 2020-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200519_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsemovieinfo',
            old_name='describe',
            new_name='full_describe',
        ),
        migrations.AddField(
            model_name='parsemovieinfo',
            name='short_describe',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsemovieinfo',
            name='source_link',
            field=models.SlugField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsemovieinfo',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='parsemovieinfo',
            name='url',
            field=models.SlugField(max_length=300),
        ),
    ]
