# Generated by Django 3.0.6 on 2020-05-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200519_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsemovieinfo',
            name='source_link',
        ),
    ]
