# Generated by Django 3.0.6 on 2020-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articlecomment_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='id_article',
            field=models.IntegerField(),
        ),
    ]
