# Generated by Django 3.0.6 on 2020-05-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200526_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='id_article_reply',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ParseMovieInfo'),
        ),
    ]
