# Generated by Django 3.0.6 on 2020-05-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200526_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='id_article_reply',
            new_name='id_article_reply_comment',
        ),
    ]
