# Generated by Django 3.0.6 on 2020-05-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200530_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='id_parent',
            new_name='parent',
        ),
    ]
