# Generated by Django 3.0.5 on 2020-05-01 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='media/actors/')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration_film', models.TimeField()),
                ('desc', models.TextField()),
                ('year', models.DateField()),
                ('contry', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('premiere', models.CharField(max_length=150)),
                ('budget', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/posters/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_hall', models.IntegerField()),
                ('number_of_row', models.IntegerField()),
                ('number_of_seats_in_a_row', models.IntegerField()),
                ('spaciousness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.IntegerField()),
                ('row_number', models.IntegerField()),
                ('id_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time_start', models.TimeField()),
                ('id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Film')),
                ('id_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_paid', models.BooleanField(default=False)),
                ('date_created_ticket', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('reservation_ticket', models.BooleanField(default=False)),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Place')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sector', models.CharField(max_length=150)),
                ('id_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('id_sector_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sector')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Session')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Genre'),
        ),
    ]
