# Generated by Django 3.0.5 on 2020-05-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200502_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
    ]
