# Generated by Django 3.0.5 on 2020-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200502_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.TextField(default='SOME STRING', verbose_name='Описание'),
        ),
    ]
