# Generated by Django 3.0.5 on 2020-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200503_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='url_trailer',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
