# Generated by Django 3.0.5 on 2020-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200503_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='url_trailer',
            field=models.CharField(max_length=200),
        ),
    ]
