# Generated by Django 3.0.5 on 2020-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_place_id_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='biography',
            field=models.TextField(default=0, verbose_name='Биография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='birthplace',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='career',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='citizenship',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
