# Generated by Django 3.0.5 on 2020-05-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200506_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description',
        ),
    ]
