# Generated by Django 3.0.5 on 2020-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='price_sector',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
