# Generated by Django 3.0.5 on 2020-05-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_time_sessions_type_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price_session',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
