# Generated by Django 3.0.5 on 2020-05-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_session_price_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
