# Generated by Django 3.0.5 on 2020-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reservation_ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_paid',
            field=models.PositiveIntegerField(),
        ),
    ]
