# Generated by Django 3.0.5 on 2020-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_ticket_date_created_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('weekday', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
