# Generated by Django 3.0.5 on 2020-05-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='weekday_en',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
