# Generated by Django 3.0.5 on 2020-05-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='id_film_id',
            new_name='id_film',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='id_user_id',
            new_name='id_user',
        ),
    ]
