# Generated by Django 3.0.6 on 2020-06-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200529_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Comments', verbose_name='Родитель'),
        ),
    ]
