# Generated by Django 3.0.6 on 2020-06-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_comments_id_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='id_hall',
        ),
        migrations.AddField(
            model_name='sector',
            name='id_hall',
            field=models.ManyToManyField(to='app.Hall'),
        ),
    ]
