# Generated by Django 3.0.6 on 2020-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200613_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
