# Generated by Django 3.0.6 on 2020-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200614_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthplace_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='birthplace_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='career_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='career_uk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='citizenship_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='citizenship_uk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_uk',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
