# Generated by Django 3.0.6 on 2020-06-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200614_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name_cinema', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
