# Generated by Django 3.0.6 on 2020-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_name_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='barcode',
            field=models.ImageField(default=0, upload_to='tikets/'),
            preserve_default=False,
        ),
    ]
